gui_main.h: remove unused variable
GCC 10's default '-fno-common' does not like it:

| ... git/build/../src/gui_main.h:31: multiple definition of `user_friendly_id'; ..

Signed-off-by: Andreas Müller <schnitzeltony@gmail.com>